### ISSUE TITLE
Back to basics sessions

### ISSUE THREAD

**Issue by sayanee** [sayanee/hackware#3]
As decided, we will be having a 10 minutes talk every session called **Back to Basics**. Here's a list of potential topics:
- [ ] Physics and electronics laws
- [ ] Soldering
- [ ]  Logic Gates

cc: @fazman @yeokm1 @notthetup @Nexus7 @catmaker  

Please suggest more topics and I will add on above: https://www.facebook.com/groups/hackware/

**Comment by notthetup** [comment]
- Soldering (Component Sizes, Irons, Tips, Solder, Flux, Reflow, etc)
- PCB (Layout, Material, Layers, Masks, SilkScreen, etc)
- Batteries (Voltage, Amperage, Capacity (Voltage, Current, Power), Chemistry )
- Power Regulators (LDO, SMPS, Efficiency, Buck, Boost)

**Comment by adnan-aj** [comment]
Simple demo of Class A, B, D audio amplifiers
OpAmps and audio
(Is it we suggest here or is there a hackware thread?)
